### ISSUE TITLE
"Fill category thumbnails" option removes "Category Image" on run

### ISSUE THREAD

**Issue by rommmka** [swissup/module-easycatalogimg#10]
- Upload category image. Save
- Go to ECI, check "Fill category thumbnails"  and Run
- Observe the Category image removed.
- ¯\_(ツ)_/¯

**Comment by vovayatsyuk** [comment]
I can't reproduce this behavior. For me, the thumbnail appeared and the category image is still the same as before.

**Comment by vovayatsyuk** [comment]
2.4.3-p1 works fine too.

@rommmka can you reproduce it locally on your PC?
