### ISSUE TITLE
Consider improve image helper `resize` method

### ISSUE THREAD

**Issue by tangar76** [swissup/module-easycatalogimg#13]
It can be helpful when there are issues with image resize.
For example in make case I have difficulties with module `Magecomp_Webpimages`. I adds support of WebP images into Magento 2. And allows to upload then as category thumbnails. But when Easy Catalog Images tries to resize them exception occurs. Exception about invalid format. And as result no images in subcategories list.

I offer next change to improve module stability:

```diff
--- /Helper/Image.php
+++ /Helper/Image.php (Unsaved)
@@ -110,7 +110,11 @@
             $image->save($cacheDir . '/' . $imageName);
             return $cacheUrl . $imageName;
         } catch (\Exception $e) {
-            return false;
+
+            $baseDir = $this->getBaseDir();
+            $baseUrl = $this->getBaseUrl();
+
+            return str_replace($baseDir, $baseUrl, $imageFile);
         }
     }
     /**
```

**Comment by vovayatsyuk** [comment]
Nice! Let's do that!

p.s. Does this module provide a resize support? If yes, can we rewrite our code to support it?
