### ISSUE TITLE
Add new slider block with selected category 

### ISSUE THREAD

**Issue by dimdimich** [swissup/module-easycatalogimg#9]
Please check 
![Screenshot_2021-05-28 Dog Supplies Best Dog Puppy Products (Free Shipping) Chewy](https://user-images.githubusercontent.com/5389109/119989500-883c9180-bfc7-11eb-8c7c-c957667c7a8c.png)
https://www.chewy.com/b/dog-288

**Comment by roma84** [comment]
https://docs.swissuplabs.com/m2/argento/home/page-structure/homepage/#the-essentials

**Comment by roma84** [comment]
We can add such element to elements page as example

**Comment by dimdimich** [comment]
Yes will be good idea.
